---
concurrency: 3
queues:
  - "debit"
  - "credit"
  - "webhooks"
  - "check.statements"
  - "check.orders"
  - "check.activations"
schedule:
  update_processing_status:
    every: "6h"
    class: Box::Jobs::QueueProcessingStatus
    queue: "check.orders"
  fetch_account_statements:
    every: "60m"
    class: Box::Jobs::FetchStatements
    queue: "check.statements"
  activate_ebics_user:
    every: "60m"
    class: Box::Jobs::CheckActivation
    queue: "check.activations"
  fetch_upcoming_account_statements:
    every: "60m"
    class: Box::Jobs::FetchUpcomingStatements
    queue: "check.statements"
dynamic: true
